from __future__ import annotations

from typing import Any

from src.agents.state import AgentState
from src.integration.plane_client import PlaneClient

COMPASS_COMMENT_MARKER = "Generated by COMPASS AI"


def build_basic_plane_comment(state: AgentState) -> str:
    if not state.top_candidates:
        return (
            "## COMPASS AI Recommendation\n\n"
            "Recommendation was not generated: no candidates found.\n\n"
            f"<!-- {COMPASS_COMMENT_MARKER} -->"
        )

    top = state.top_candidates[0]

    lines = [
        "## COMPASS AI Recommendation",
        "",
        f"Recommended assignee: **{top.get('name')}**",
        f"Mode: `{state.recommendation_mode}`",
        f"Score: `{top.get('score')}`",
        "",
        "### Top candidates",
    ]

    for candidate in state.top_candidates:
        lines.append(
            f"{candidate.get('rank')}. {candidate.get('name')} "
            f"— `{candidate.get('score')}`"
        )

    lines.extend(
        [
            "",
            "### Explanation",
            state.explanation,
            "",
            "Note: this is a decision-support recommendation. "
            "Final assignment is made by the team lead.",
            "",
            f"<!-- {COMPASS_COMMENT_MARKER} -->",
        ]
    )

    return "\n".join(lines)


def load_plane_work_item(
    project_id: str,
    work_item_id: str,
    client: PlaneClient | None = None,
) -> dict[str, Any]:
    client = client or PlaneClient()
    return client.get_work_item(project_id=project_id, work_item_id=work_item_id)


def existing_compass_comment_exists(
    project_id: str,
    work_item_id: str,
    client: PlaneClient | None = None,
) -> bool:
    client = client or PlaneClient()
    comments = client.list_work_item_comments(
        project_id=project_id,
        work_item_id=work_item_id,
    )

    results = comments.get("results", comments if isinstance(comments, list) else [])

    for comment in results:
        text = " ".join(
            [
                str(comment.get("comment_html", "")),
                str(comment.get("comment_stripped", "")),
                str(comment.get("text", "")),
            ]
        )

        if COMPASS_COMMENT_MARKER in text:
            return True

    return False


def write_recommendation_comment(
    state: AgentState,
    project_id: str,
    work_item_id: str,
    client: PlaneClient | None = None,
) -> dict[str, Any]:
    client = client or PlaneClient()

    if existing_compass_comment_exists(project_id, work_item_id, client):
        return {
            "status": "skipped",
            "reason": "COMPASS AI comment already exists.",
        }

    comment_text = build_basic_plane_comment(state)

    response = client.create_work_item_comment(
        project_id=project_id,
        work_item_id=work_item_id,
        text=comment_text,
    )

    return {
        "status": "created",
        "response": response,
    }


def run_plane_agent(
    state: AgentState,
    project_id: str | None = None,
    work_item_id: str | None = None,
    write_back: bool = False,
) -> AgentState:
    if not write_back:
        return state

    if not project_id or not work_item_id:
        state.add_error(
            "plane_agent",
            "project_id and work_item_id are required for write_back.",
        )
        return state

    try:
        write_result = write_recommendation_comment(
            state=state,
            project_id=project_id,
            work_item_id=work_item_id,
        )
        state.final_response["plane_write_back"] = write_result
    except Exception as error:
        state.add_error("plane_agent", str(error))

    return state