from __future__ import annotations

from typing import Any

COMMENT_MARKER = "Generated by COMPASS AI"


def _safe_text(value: Any, default: str = "") -> str:
    if value is None:
        return default

    text = str(value).strip()

    if text.lower() in {"nan", "none", "null"}:
        return default

    return text


def _safe_float(value: Any, default: float = 0.0) -> float:
    try:
        return float(value)
    except (TypeError, ValueError):
        return default


def _format_score(value: Any) -> str:
    return f"{_safe_float(value):.4f}"


def _candidate_title(candidate: dict[str, Any]) -> str:
    name = _safe_text(candidate.get("name"), "Unknown employee")
    role = _safe_text(candidate.get("role"), "unknown_role")
    grade = _safe_text(candidate.get("grade"), "unknown_grade")

    return f"{name} ({role}, {grade})"


def _candidate_factor(candidate: dict[str, Any], factor_name: str) -> str:
    factors = candidate.get("factors") or {}

    if not isinstance(factors, dict):
        return "n/a"

    value = factors.get(factor_name)

    if value is None:
        return "n/a"

    return _format_score(value)


def _format_risks(candidate: dict[str, Any]) -> str:
    risks = candidate.get("risks") or []

    if not risks:
        return "no major risks detected"

    if isinstance(risks, str):
        return risks

    return "; ".join(str(risk) for risk in risks)


def _format_reasons(candidate: dict[str, Any]) -> str:
    reasons = candidate.get("reasons") or []

    if not reasons:
        return "ranking is based on model score and recommendation mode factors"

    if isinstance(reasons, str):
        return reasons

    return "; ".join(str(reason) for reason in reasons)


def _top_candidates(recommendation: dict[str, Any], limit: int = 3) -> list[dict[str, Any]]:
    candidates = recommendation.get("top_candidates") or recommendation.get("candidates") or []

    if not isinstance(candidates, list):
        return []

    return [candidate for candidate in candidates[:limit] if isinstance(candidate, dict)]


def _format_top_candidates(candidates: list[dict[str, Any]]) -> str:
    if not candidates:
        return "No candidates were produced."

    lines: list[str] = []

    for index, candidate in enumerate(candidates, start=1):
        rank = int(candidate.get("rank") or index)
        title = _candidate_title(candidate)
        score = _format_score(candidate.get("score"))
        success_probability = candidate.get("success_probability")
        source = _safe_text(candidate.get("source"), "unknown")

        probability_part = ""
        if success_probability is not None:
            probability_part = f", success_probability={_format_score(success_probability)}"

        lines.append(
            f"{rank}. **{title}** — score={score}{probability_part}, source={source}"
        )
        lines.append(
            "   - factors: "
            f"skill={_candidate_factor(candidate, 'skill_match')}, "
            f"risk={_candidate_factor(candidate, 'risk')}, "
            f"workload={_candidate_factor(candidate, 'workload_pressure')}, "
            f"growth={_candidate_factor(candidate, 'growth_match')}, "
            f"quality={_candidate_factor(candidate, 'quality')}, "
            f"deadline_reliability={_candidate_factor(candidate, 'deadline_reliability')}"
        )
        lines.append(f"   - reasons: {_format_reasons(candidate)}")
        lines.append(f"   - risks: {_format_risks(candidate)}")

    return "\n".join(lines)


def _format_explanation(explanation: Any) -> str:
    text = _safe_text(explanation)

    if not text:
        return "No explanation was generated."

    return text


def format_plane_recommendation_comment(recommendation: dict[str, Any]) -> str:
    candidates = _top_candidates(recommendation)
    top_candidate = candidates[0] if candidates else {}

    task_title = _safe_text(recommendation.get("title"), "Untitled task")
    task_type = _safe_text(recommendation.get("task_type"), "unknown_task_type")
    mode = _safe_text(recommendation.get("mode"), "balanced_workload")
    source = _safe_text(recommendation.get("source"), "agentic_pipeline")
    recommended_assignee = _candidate_title(top_candidate) if top_candidate else "No recommendation"
    recommended_score = _format_score(top_candidate.get("score")) if top_candidate else "n/a"
    explanation = _format_explanation(recommendation.get("explanation"))

    return "\n".join(
        [
            "## COMPASS AI Recommendation",
            "",
            f"**Task:** {task_title}",
            f"**Task type:** `{task_type}`",
            f"**Mode:** `{mode}`",
            f"**Recommended assignee:** {recommended_assignee}",
            f"**Score:** `{recommended_score}`",
            f"**Source:** `{source}`",
            "",
            "### Top candidates",
            "",
            _format_top_candidates(candidates),
            "",
            "### Explanation",
            "",
            explanation,
            "",
            "### Decision note",
            "",
            (
                "This is a decision-support recommendation. "
                "Final assignment is made by the team lead."
            ),
            "",
            f"_{COMMENT_MARKER}_",
        ]
    )


def has_compass_marker(text: Any) -> bool:
    return COMMENT_MARKER.lower() in _safe_text(text).lower()