from __future__ import annotations

import html
import json
from datetime import date, timedelta
from typing import Any

STACK_TO_LABEL: dict[str, str] = {
    "Python": "python",
    "FastAPI": "fastapi",
    "Django": "django",
    "PostgreSQL": "postgresql",
    "Redis": "redis",
    "Docker": "docker",
    "Kubernetes": "kubernetes",
    "React": "react",
    "TypeScript": "typescript",
    "Next.js": "nextjs",
    "HTML/CSS": "html-css",
    "PyTorch": "pytorch",
}


TASK_TYPE_TO_LABELS: dict[str, list[str]] = {
    "backend_feature": ["backend", "feature"],
    "frontend_feature": ["frontend", "feature"],
    "bugfix": ["bug"],
    "refactoring": ["refactoring"],
    "database_migration": ["backend", "data"],
    "api_integration": ["backend", "feature"],
    "ml_pipeline": ["ml", "data"],
    "analytics_report": ["data"],
    "devops_task": ["devops"],
    "testing_task": ["testing"],
    "security_task": ["security"],
    "documentation_task": ["documentation"],
}


PROJECT_KEY_TO_IDENTIFIER: dict[str, str] = {
    "BACK": "BACK",
    "FRONT": "FRONT",
    "DATA": "DATA",
    "TOOLS": "TOOLS",
}


def parse_json_cell(value: Any, default: Any) -> Any:
    if value is None:
        return default

    if isinstance(value, float) and str(value) == "nan":
        return default

    if isinstance(value, str):
        value = value.strip()

        if not value:
            return default

        return json.loads(value)

    return value


def normalize_priority(priority: str | None) -> str:
    if not priority:
        return "medium"

    value = str(priority).strip().lower()

    if value in {"none", "low", "medium", "high", "urgent"}:
        return value

    return "medium"


def normalize_label_name(label: str) -> str:
    return (
        str(label)
        .strip()
        .lower()
        .replace(" ", "-")
        .replace("_", "-")
        .replace("/", "-")
    )


def labels_for_task(task: dict[str, Any]) -> list[str]:
    labels: set[str] = set()

    task_type = str(task.get("task_type", "")).strip()
    labels.update(TASK_TYPE_TO_LABELS.get(task_type, []))

    required_stack = parse_json_cell(task.get("required_stack"), default=[])

    for stack_item in required_stack:
        label = STACK_TO_LABEL.get(str(stack_item), str(stack_item))
        labels.add(normalize_label_name(label))

    if bool(task.get("is_growth_task")):
        labels.add("growth-task")

    if normalize_priority(str(task.get("priority"))) == "urgent":
        labels.add("urgent")

    return sorted(labels)


def target_date_from_deadline(deadline_days: int | float | str | None) -> str | None:
    if deadline_days is None:
        return None

    try:
        days = int(float(deadline_days))
    except ValueError:
        return None

    if days <= 0:
        return None

    return (date.today() + timedelta(days=days)).isoformat()


def task_description_html(task: dict[str, Any]) -> str:
    description = html.escape(str(task.get("description", "")).strip())
    task_id = html.escape(str(task.get("task_id", "")).strip())
    task_type = html.escape(str(task.get("task_type", "")).strip())
    complexity = html.escape(str(task.get("complexity", "")).strip())
    estimated_hours = html.escape(str(task.get("estimated_hours", "")).strip())
    required_skills = html.escape(str(task.get("required_skills", "")).strip())

    return (
        f"<p>{description}</p>"
        "<hr />"
        "<p><strong>Generated by COMPASS AI synthetic data seed.</strong></p>"
        f"<p>COMPASS_TASK_ID={task_id}</p>"
        f"<p><strong>COMPASS task_id:</strong> {task_id}</p>"
        f"<p><strong>Task type:</strong> {task_type}</p>"
        f"<p><strong>Complexity:</strong> {complexity}</p>"
        f"<p><strong>Estimated hours:</strong> {estimated_hours}</p>"
        f"<p><strong>Required skills:</strong> {required_skills}</p>"
    )


def task_to_plane_work_item_payload(
    task: dict[str, Any],
    label_name_to_id: dict[str, str],
) -> dict[str, Any]:
    label_names = labels_for_task(task)
    label_ids = [
        label_name_to_id[label_name]
        for label_name in label_names
        if label_name in label_name_to_id
    ]

    payload: dict[str, Any] = {
        "name": str(task["title"]),
        "description_html": task_description_html(task),
        "priority": normalize_priority(str(task.get("priority"))),
        "labels": label_ids,
    }

    target_date = target_date_from_deadline(task.get("deadline_days"))
    if target_date:
        payload["target_date"] = target_date

    return payload


def task_project_id(task: dict[str, Any]) -> str:
    project_id = str(task.get("plane_project_id", "")).strip()

    if not project_id:
        raise ValueError(f"Task {task.get('task_id')} does not have plane_project_id.")

    return project_id


def compass_task_marker(task_id: str) -> str:
    return f"COMPASS_TASK_ID={task_id}"